### ISSUE TITLE
Wiring for BUCK Converter?

### ISSUE THREAD

**Issue by insestito36** [A-Emile/Lime_Gen3_IoT_Replacement#13]
Hello! First of all, thank you for all your efforts making this repository for make personal LIME gen 3.
Can you write how to wiring the BUCK converter? Is this "wiring diagram" correct?

PIN 4 (Controller 36V)----------------      ( In+   BUCK CONV.  Out+   ) ------- (Input AMS1117  -  OUT 5V AMS1117 )  -- ESP32 ? Or ESP32 and display?
PIN 6 (Controller GND)---------------      ( In-    BUCK CONV.   Out-) --------(GND AMS1117   -   GND AMS1117)  --- ESP32 ? Or ESP32 an Display?

**Comment by insestito36** [comment]
And when i open LIMER apk it says "Authorize the flutterreactiveble example app to use bluetooth and location" What this mean?

**Comment by RSF99** [comment]
check the other comments

**Comment by aIecxs** [comment]
Respect the Code of Conduct

GitHub issues are primarily for discussing code-related topics, such as bug reports, feature requests, and improvements to the project. If you have a general question or need help troubleshooting, it's best to look for more appropriate channels, such as forums or dedicated community spaces.

Recognize that GitHub issues are a resource for project maintainers to manage and prioritize work. Posting non-code-related questions or comments in issues will create noise and make it difficult for maintainers to focus on actual development tasks.

(comment can be deleted)
