### ISSUE TITLE
Send display error

### ISSUE THREAD

**Issue by Tonka7aBG** [A-Emile/Lime_Gen3_IoT_Replacement#22]
So when i flash LimeIoT , i have error sendDisplayCommand was not declared in this scope , and i dont know whats the problem. I tried with arduino 1.8 but the problem still exists. The esp software from library is the last version.
![Screenshot_20240920_005632_Instagram](https://github.com/user-attachments/assets/42c94520-b3ec-415c-bbec-9156d3d81ed5)

**Comment by G-Redos** [comment]
How did you upload all the files to the ESP32?

**Comment by Tonka7aBG** [comment]
> How did you upload all the files to the ESP32?

I load only LimeIoT file from sketch menu.

**Comment by G-Redos** [comment]
What about the rest of the files from the LimeIoT folder?

**Comment by Tonka7aBG** [comment]
> What about the rest of the files from the LimeIoT 

> What about the rest of the files from the LimeIoT folder?

How i can upload all the files? And when i try to upload something else from that folder i had another error.

**Comment by G-Redos** [comment]
What is the process you used, to upload all the files?
Step by step.

**Comment by Tonka7aBG** [comment]
> What is the process you used, to upload all the files? Step by step.

One by one from the folder and then select upload.

**Comment by G-Redos** [comment]
Use this method:
**https://www.youtube.com/watch?v=9i1nDUoDRcI**

**Comment by G-Redos** [comment]
You then should see tabs, in your Arduino IDE, with all the files open.
