### ISSUE TITLE
Pin numbers 

### ISSUE THREAD

**Issue by gc9n** [A-Emile/Lime_Gen3_IoT_Replacement#25]
What exactly pin #1 into this pin headers? 
I will desolder and use this one.
![IMG_20241015_181809](https://github.com/user-attachments/assets/6ce4272a-f90c-4445-8046-4f5bb33cf506)

**Comment by G-Redos** [comment]
The cables have colors.
Each cable has a connection to a specific GPIO.

**Comment by gc9n** [comment]
Thanks for your answer , 
So i follow the colours of this diagram to the actual connector 
i see on the cable harness , Pin 3 and Pin 4 are Red coloured , ok i will use a multimeter.

![image](https://github.com/user-attachments/assets/ca089352-45c7-4d24-a7a7-23da79904c51)

**Comment by aIecxs** [comment]
the numbering of the connector is not correct. you can look into datasheet [here](https://www.tme.eu/en/details/df13ea20dp1.25v65/raster-signal-connectors-1-25mm/hirose/df13ea-20dp-1-25v-65) the pin numbering is 180° turned.

**Comment by gc9n** [comment]
Let me ask again maybe I didn't asked the question correctly 

I want to desolder this and solder ON it the ESP32 pins.
However I don't know the numbering .
I will take a look on the datasheet you send me thanks 

![17290836852831157046421580343420](https://github.com/user-attachments/assets/472bc5a4-2d9a-4dce-afca-ca1b54f92131)

**Comment by G-Redos** [comment]
Look at your ESP32.
They have specific GPIO pins.
The cables are color coded.
You have two cables, one from the main controller, and the other from the display.
The color coded cables, go specifically to the designated GPIO pin to the ESP32.

Yes it is possible, to do what you want.
But you will have to match the cable layout to the GPIO pin layout of the ESP32.

**Comment by aIecxs** [comment]
Yes, I had already understood that. I said the connector is rotated by 180° degree. See the triangle marking on the connector, Pin 1 = Display TX.
![IMG_20241017_120703](https://github.com/user-attachments/assets/99f6521e-6750-4cb3-9a07-9550419b0f03)

Here is the full pinout:
https://forum.xda-developers.com/posts/89114905

**Comment by gc9n** [comment]
thanks guys

**Comment by gc9n** [comment]
![IMG_20241017_154927](https://github.com/user-attachments/assets/577bf442-bacc-48f9-b6b0-cdd8fceabc9b)
I am 1% before I finish 
Can you guys explain controller lock goes to GPIO12?
And COntroller charge to pin 2??

**Comment by gc9n** [comment]
![IMG_20241017_161903](https://github.com/user-attachments/assets/7361cdfe-f84b-4804-ace5-36c697b16ef7)
Everything is Flawless 
The only problem is that the battery shows 0%

**Comment by gc9n** [comment]
I doubled checked everything 
 
Throttle working
Light working 
Battery is 0% but is 100%
And km per h are. 0 which is false.

Ps the controller is flashed with st link from the known place

**Comment by gc9n** [comment]
the controller is flashed with 
[https://www.dropbox.com/scl/fo/v255vxco67f128a9j56qc/ADV5v-_SYfOrOjPAkJEbjjs/LIME%20File/HEX%20Backup?dl=0&rlkey=q2jcr5qzxdxrdi34t774icoog&subfolder_nav_tracking=1
](LINK )
the Unlocked 25k

**Comment by gc9n** [comment]
long story short everything is working , even the brake light , motor is working, 
i just get no info for Speed and Battery, i am chinging the code that i use

https://github.com/aIecxs/Lime_Gen3_IoT_Replacement/blob/2.3.x/LimeIoT/LimeIoT.ino

**Comment by aIecxs** [comment]
when you connect the charger does it display battery charging?

**Comment by gc9n** [comment]
> when you connect the charger does it display battery charging?

Even though pin2 is connected to GPIO33  doesnt give me the status.  
So I assume that 
something is wrong on the readController()  , apparently the incoming bytes are not read correctly , 
i already update the "silver "  controller  to locked 25  , unlocked 25 with the same results.
theres is no communication with the serial on the controller , 
i will double check if i messed the TX RX pins

PS  My Sketch is the 2.3.x

**Comment by gc9n** [comment]
No , its code related the TX RX ESP32 <-> RX TX CONtroller   is fine ,
and also the GPIO33 is not related to the UART communication

**Comment by gc9n** [comment]
The light Command is working just fine.... very weird.   so there is communication with the Controller and the ESP however some incoming value are not recognized?

**Comment by aIecxs** [comment]
When charger is connected, the controller is powered on automatically and is continuously sending data, regardless of the lock state. Use any USB to UART Bridge (CP2102 or CH340 or something) to verify the data is sent/received on GPIO 1 + 3.

The front light is controlled by the display controller on GPIO 16 + 17.

**Comment by gc9n** [comment]
What CRC library do i have to use?  i am using 1.0.3 Rob tillard

**Comment by gc9n** [comment]
Ok i tried my module , on another set of Controller/monitor and is working , battery and speed, 
So i guess is cable related, i dont know wich on have to find out

**Comment by G-Redos** [comment]
What do you mean exactly, you connected your setup with the ESP32 to another device and the results are working as they should?

**Comment by gc9n** [comment]
i have no idea why , but it works now , i uninstall and reinstall all the cables , and is fine

**Comment by G-Redos** [comment]
Cables connecting the IOT port to the ESP32, or the main cables from the motor controller to the ESP32?
