### ISSUE TITLE
 2 3.x (themed) branch  And Bluetooth 

### ISSUE THREAD

**Issue by gc9n** [A-Emile/Lime_Gen3_IoT_Replacement#27]
hi ,  2 3.x (themed) branch  the Bluetooth  cannot be paired , i changed the password , but nothing, password variable doesnt even used anywhere

**Comment by gc9n** [comment]
setup.ino line 111 theres a hardcoded pass 123456

**Comment by aIecxs** [comment]
kindly read the instructions before open new issues. I have quoted the relevant section below:

> The default bluetooth password is `123456789`. You can change it in the [ble_security.ino](../../tree/HEAD/LimeIoT/ble_security.ino) file.

If you're asking especially for the themed branch, please also read the instructions of the relevant branch #26:

> If you forgot to upload mp3 files, the [themed](../../tree/themed) branch will crash the ESP32 when playing audio / file not found.

**Comment by aIecxs** [comment]
Kindly read the instructions more carefully. For troubleshooting, please visit the [forum](https://scootertalk.org/forum/viewtopic.php?t=5474&start=180). You're more likely to get help there than by spamming the GitHub issues.

Regarding #28 let me emphasize once more what you might have missed:
[![IMG_20241017_130041](https://github.com/user-attachments/assets/f40e66d9-84ab-467b-a7a3-ca4212b9ae28)](https://randomnerdtutorials.com/arduino-ide-2-install-esp32-littlefs/#installing-windows)
